// Font Awesome icon → Lucide icon (lucide.dev), for the theme setting
// lucide_icons. scripts/theme/icons.mts builds assets/icons-sprite.svg from
// this (`pnpm theme:icons`), and api-initializers/jt-lucide-icons points
// Discourse's icons at the sprite. Plain data, no imports: the build script
// reads it too.
//
// Brand icons (fab-*) and icons not listed keep Font Awesome.
export const JT_ICON_MAP: Record<string, string> = {
  "address-book": "book-user",
  "address-card": "id-card",
  anchor: "anchor",
  "angle-down": "chevron-down",
  "angle-left": "chevron-left",
  "angle-right": "chevron-right",
  "angle-up": "chevron-up",
  "angles-down": "chevrons-down",
  "angles-up": "chevrons-up",
  "arrow-down": "arrow-down",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "arrow-rotate-left": "rotate-ccw",
  "arrow-trend-up": "trending-up",
  "arrow-up": "arrow-up",
  "arrow-up-from-bracket": "share",
  "arrows-rotate": "refresh-cw",
  asterisk: "asterisk",
  at: "at-sign",
  award: "award",
  ban: "ban",
  bars: "menu",
  "bars-staggered": "text-align-start",
  bed: "bed",
  bell: "bell",
  "bell-slash": "bell-off",
  bold: "bold",
  bolt: "zap",
  book: "book",
  "book-open": "book-open",
  "book-open-reader": "book-open",
  bookmark: "bookmark",
  "box-archive": "archive",
  "cake-candles": "cake",
  "calendar-days": "calendar-days",
  certificate: "badge-check",
  "chart-bar": "chart-column",
  "chart-line": "chart-line",
  check: "check",
  "chevron-down": "chevron-down",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  "chevron-up": "chevron-up",
  circle: "circle",
  "circle-check": "circle-check",
  "circle-dot": "circle-dot",
  "circle-exclamation": "circle-alert",
  "circle-half-stroke": "sun-moon",
  "circle-info": "info",
  "circle-plus": "circle-plus",
  "circle-question": "circle-question-mark",
  "circle-user": "circle-user",
  "circle-xmark": "circle-x",
  clipboard: "clipboard",
  clock: "clock",
  "clock-rotate-left": "history",
  code: "code",
  "code-branch": "git-branch",
  copy: "copy",
  crown: "crown",
  database: "database",
  desktop: "monitor",
  "diagram-project": "workflow",
  "discourse-bell-exclamation": "bell-ring",
  "discourse-bell-one": "bell-dot",
  "discourse-bell-slash": "bell-off",
  "discourse-bookmark-clock": "bookmark",
  "discourse-compress": "minimize-2",
  "discourse-emojis": "smile-plus",
  "discourse-expand": "maximize-2",
  "discourse-other-tab": "layout-grid",
  "discourse-sparkles": "sparkles",
  "discourse-text": "heading",
  "discourse-threads": "messages-square",
  "down-left-and-up-right-to-center": "minimize-2",
  download: "download",
  "earth-americas": "earth",
  ellipsis: "ellipsis",
  "ellipsis-vertical": "ellipsis-vertical",
  envelope: "mail",
  expand: "expand",
  eye: "eye",
  "eye-slash": "eye-off",
  "face-smile": "smile",
  "far-bell": "bell",
  "far-bookmark": "bookmark",
  "far-calendar": "calendar",
  "far-chart-bar": "chart-column",
  "far-circle": "circle",
  "far-clock": "clock",
  "far-comment": "message-circle",
  "far-comments": "messages-square",
  "far-copy": "copy",
  "far-envelope": "mail",
  "far-eye": "eye",
  "far-face-smile": "smile",
  "far-heart": "heart",
  "far-image": "image",
  "far-pen-to-square": "square-pen",
  "far-square": "square",
  "far-square-check": "square-check",
  "far-trash-can": "trash-2",
  file: "file",
  "file-signature": "file-signature",
  filter: "funnel",
  fire: "flame",
  flag: "flag",
  flask: "flask-conical",
  folder: "folder",
  font: "type",
  gear: "settings",
  gift: "gift",
  globe: "globe",
  hand: "hand",
  headset: "headset",
  heart: "heart",
  "hourglass-start": "hourglass",
  house: "house",
  image: "image",
  images: "images",
  inbox: "inbox",
  italic: "italic",
  keyboard: "keyboard",
  language: "languages",
  "layer-group": "layers",
  "left-right": "move-horizontal",
  link: "link",
  list: "list",
  "list-check": "list-checks",
  "list-ol": "list-ordered",
  "list-ul": "list",
  lock: "lock",
  "magnifying-glass": "search",
  microphone: "mic",
  minus: "minus",
  "mobile-screen-button": "smartphone",
  moon: "moon",
  paintbrush: "paintbrush",
  "paper-plane": "send",
  paperclip: "paperclip",
  "pen-to-square": "square-pen",
  pencil: "pencil",
  play: "play",
  plus: "plus",
  print: "printer",
  "puzzle-piece": "puzzle",
  qrcode: "qr-code",
  question: "circle-question-mark",
  "quote-left": "quote",
  "quote-right": "quote",
  reply: "reply",
  "right-from-bracket": "log-out",
  "right-left": "arrow-left-right",
  "right-to-bracket": "log-in",
  robot: "bot",
  rocket: "rocket",
  rotate: "rotate-cw",
  rss: "rss",
  "screwdriver-wrench": "wrench",
  scroll: "scroll-text",
  share: "forward",
  "share-nodes": "share-2",
  "shield-halved": "shield-half",
  sliders: "sliders-horizontal",
  "square-check": "square-check",
  "square-full": "square",
  "square-root-variable": "radical",
  star: "star",
  stop: "square",
  strikethrough: "strikethrough",
  sun: "sun",
  table: "table",
  "table-cells": "grid-3x3",
  tag: "tag",
  "thumbs-up": "thumbs-up",
  thumbtack: "pin",
  "trash-can": "trash-2",
  "triangle-exclamation": "triangle-alert",
  trophy: "trophy",
  unlock: "lock-open",
  "up-right-from-square": "external-link",
  upload: "upload",
  user: "user",
  "user-gear": "user-cog",
  "user-group": "users",
  "user-plus": "user-plus",
  "user-secret": "hat-glasses",
  "user-shield": "shield-user",
  users: "users",
  "wand-magic": "wand",
  wrench: "wrench",
  xmark: "x",
};

// Font Awesome's solid icons that mean "on" next to an outline "off" (liked
// vs not, bookmarked vs not): drawn filled so the state still shows.
export const JT_FILLED_ICONS: readonly string[] = [
  "bookmark",
  "circle",
  "heart",
  "square-full",
  "star",
];

// The sprite's symbol for a Font Awesome icon
export function jtIconId(faIcon: string): string | undefined {
  const lucide = JT_ICON_MAP[faIcon];
  if (!lucide) {
    return undefined;
  }
  return JT_FILLED_ICONS.includes(faIcon)
    ? `jt-${lucide}-fill`
    : `jt-${lucide}`;
}
