// Builds Dumbcourse from TypeScript and SCSS into the files the plugin serves:
//
//   public/dumbcourse.js   one ES5 script (no ES2015+ syntax at all)
//   public/dumbcourse.css  one stylesheet whose var() uses carry fallbacks
//   public/index.html      the page template (page.ts)
//
// The pipeline is esbuild (bundle the modules into one IIFE) → TypeScript
// (lower everything to ES5, async/await included) → esbuild (minify, still
// ES5) → espree (parse as ECMAScript 5; any newer syntax fails the build).
// The browsers Dumbcourse is for — flip phones, KaiOS, old Android
// WebViews — never see anything they cannot run.
//
//   node --experimental-strip-types dumbcourse/build.ts           build
//   node --experimental-strip-types dumbcourse/build.ts --check   fail if the
//                                                   committed files are stale

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";
import * as espree from "espree";
import ts from "typescript";
import { buildCss } from "./css.ts";
import { PAGE } from "./page.ts";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const srcDir = join(here, "src");
const outJs = join(root, "public", "dumbcourse.js");
const outEarly = join(root, "public", "dumbcourse-early.js");
const outCss = join(root, "public", "dumbcourse.css");
const outPage = join(root, "public", "index.html");
const check = process.argv.includes("--check");

const BANNER =
  "/* Dumbcourse — generated by dumbcourse/build.ts from dumbcourse/src. Do not edit by hand. */\n";

// DOM methods that old engines lack. The typings allow them, so the build
// forbids them outright; `compat.ts` has the safe equivalents.
const FORBIDDEN: Array<[RegExp, string]> = [
  [/\.closest\(/, "use closest() from compat.ts"],
  [/\.matches\(/, "use matches() from compat.ts"],
  [
    /\.(append|prepend|before|after|replaceWith|replaceChildren|toggleAttribute)\(/,
    "use appendChild/insertBefore",
  ],
  [/\.remove\(\)/, "use removeNode() from compat.ts"],
  [/\bfetch\(/, "use api.ts (XMLHttpRequest)"],
  [
    /\bnew (Event|CustomEvent|URL|URLSearchParams)\(/,
    "not available on old engines",
  ],
  [
    /\b(IntersectionObserver|ResizeObserver|MutationObserver|queueMicrotask|structuredClone)\b/,
    "not available on old engines",
  ],
  [
    /\bSymbol\b/,
    "Symbol does not exist on old engines (for…of over arrays is fine)",
  ],
  [/\{\s*passive\s*:/, "old engines read an options object as useCapture=true"],
  [/\.(scrollIntoView)\(\{/, "use scrollIntoViewIfNeeded() from dom.ts"],
];

function sourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) out.push(...sourceFiles(path));
    else if (name.endsWith(".ts")) out.push(path);
  }
  return out;
}

function lintSources(): string[] {
  const problems: string[] = [];
  for (const file of sourceFiles(srcDir)) {
    if (file.endsWith("compat.ts")) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    lines.forEach((line, i) => {
      if (/^\s*(\/\/|\*)/.test(line)) return;
      // A reviewed exception, e.g. FormData#append (XHR2, which every
      // engine that can upload has): mark the line `// old-browser-ok`.
      if (/\/\/ old-browser-ok\b/.test(line)) return;
      for (const [pattern, why] of FORBIDDEN) {
        if (pattern.test(line)) {
          problems.push(
            `${relative(root, file)}:${i + 1}: ${why}\n    ${line.trim()}`
          );
        }
      }
    });
  }
  return problems;
}

// Rewrites tagged templates `tag\`a${x}b\`` into `tag(["a","b"], x)`.
// Lowered to ES5, TypeScript would pass both the cooked and the raw strings
// (every template twice, through __makeTemplateObject). Our tags only read
// the cooked strings, so one array is enough — about a third off the file.
function taggedTemplatesToCalls(
  context: ts.TransformationContext
): ts.Transformer<ts.SourceFile> {
  const f = context.factory;
  const visit = (node: ts.Node): ts.Node => {
    if (ts.isTaggedTemplateExpression(node)) {
      const tpl = node.template;
      const strings: ts.Expression[] = [];
      const values: ts.Expression[] = [];
      // In html`` markup, indentation after a line break is just
      // whitespace: keep the line break alone. (Not a space: a newline
      // straight after <textarea> or <pre> is dropped by the parser, a space
      // would end up in the value.)
      const isHtml = ts.isIdentifier(node.tag) && node.tag.text === "html";
      const lit = (text: string) =>
        f.createStringLiteral(isHtml ? text.replace(/\n[ \t]*/g, "\n") : text);
      if (ts.isNoSubstitutionTemplateLiteral(tpl)) {
        strings.push(lit(tpl.text));
      } else {
        strings.push(lit(tpl.head.text));
        for (const span of tpl.templateSpans) {
          values.push(ts.visitNode(span.expression, visit) as ts.Expression);
          strings.push(lit(span.literal.text));
        }
      }
      return f.createCallExpression(
        ts.visitNode(node.tag, visit) as ts.Expression,
        undefined,
        [f.createArrayLiteralExpression(strings), ...values]
      );
    }
    return ts.visitEachChild(node, visit, context);
  };
  return (file) => ts.visitNode(file, visit) as ts.SourceFile;
}

async function buildJs(entry: string, banner = BANNER): Promise<string> {
  const bundled = await esbuild.build({
    entryPoints: [join(srcDir, entry)],
    bundle: true,
    format: "iife",
    // Keep async/await and classes for TypeScript to lower; esbuild only
    // bundles here.
    target: "es2017",
    write: false,
    legalComments: "none",
    charset: "ascii",
    logLevel: "silent",
  });
  const es2017 = bundled.outputFiles[0].text;

  const lowered = ts.transpileModule(es2017, {
    compilerOptions: {
      target: ts.ScriptTarget.ES5,
      // TypeScript 7 drops the ES5 target; lower with another tool before upgrading.
      ignoreDeprecations: "6.0",
      module: ts.ModuleKind.CommonJS,
      allowJs: true,
      removeComments: true,
      newLine: ts.NewLineKind.LineFeed,
    },
    fileName: "dumbcourse.js",
    reportDiagnostics: true,
    transformers: { before: [taggedTemplatesToCalls] },
  });
  if (lowered.diagnostics?.length) {
    throw new Error(
      lowered.diagnostics
        .map((d) => ts.flattenDiagnosticMessageText(d.messageText, "\n"))
        .join("\n")
    );
  }

  const minified = await esbuild.transform(lowered.outputText, {
    minify: true,
    target: "es5",
    charset: "ascii",
    legalComments: "none",
  });
  const code = banner + minified.code;

  // The guarantee: the shipped file parses as ECMAScript 5.
  espree.parse(code, { ecmaVersion: 5, sourceType: "script" });
  return code;
}

function writeOrCheck(path: string, content: string): boolean {
  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = "";
  }
  if (current === content) return true;
  if (check) {
    console.error(
      `${relative(root, path)} is out of date — run pnpm dumbcourse:build`
    );
    return false;
  }
  writeFileSync(path, content);
  console.log(
    `wrote ${relative(root, path)} (${(content.length / 1024).toFixed(1)} KB)`
  );
  return true;
}

async function main(): Promise<void> {
  const problems = lintSources();
  if (problems.length) {
    console.error(
      "Dumbcourse sources use APIs old browsers lack:\n" + problems.join("\n")
    );
    process.exit(1);
  }
  const js = await buildJs("main.ts");
  // Inlined into the page head by the server (no banner: it is hashed for
  // the Content-Security-Policy exactly as served).
  const early = (await buildJs("early.ts", "")).replace(/\n+$/, "");
  const css = BANNER + (await buildCss(join(here, "styles")));
  const ok = [
    writeOrCheck(outJs, js),
    writeOrCheck(outEarly, early),
    writeOrCheck(outCss, css),
    writeOrCheck(outPage, PAGE),
  ].every(Boolean);
  if (!ok) process.exit(1);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
