#!/usr/bin/env -S node --experimental-strip-types --no-warnings
// Builds the theme's icon sprite (themes/jtech/assets/icons-sprite.svg) from
// lucide-static, for the icons listed in lib/jt-icon-map.ts, and copies
// Lucide's licence beside it. Core serves a theme's `icons-sprite` asset
// with its own icons, so the theme can point Discourse's icons at these.
//
//   pnpm theme:icons            build
//   pnpm theme:icons --check    fail if the committed sprite is stale

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import {
  JT_FILLED_ICONS,
  JT_ICON_MAP,
  jtIconId,
} from "../../themes/jtech/javascripts/discourse/lib/jt-icon-map.ts";

const theme = new URL("../../themes/jtech/", import.meta.url).pathname;
const lucide = dirname(
  createRequire(import.meta.url).resolve("lucide-static/package.json")
);
const check = process.argv.includes("--check");

// The drawing inside one of Lucide's <svg> files
function drawing(name: string): string {
  const svg = readFileSync(join(lucide, "icons", `${name}.svg`), "utf8");
  const inner = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)?.[1];
  if (!inner) {
    throw new Error(`lucide-static has no drawing for ${name}`);
  }
  return inner
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .join("");
}

const symbols = new Map<string, string>();
for (const faIcon of Object.keys(JT_ICON_MAP).sort()) {
  const id = jtIconId(faIcon)!;
  if (symbols.has(id)) {
    continue;
  }
  const fill = JT_FILLED_ICONS.includes(faIcon) ? "currentColor" : "none";
  symbols.set(
    id,
    `<symbol id="${id}" viewBox="0 0 24 24" fill="${fill}" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${drawing(JT_ICON_MAP[faIcon])}</symbol>`
  );
}

const sprite = [
  "<!-- Lucide icons (lucide.dev, ISC licence: ../LUCIDE-LICENSE.txt). Generated by scripts/theme/icons.mts from javascripts/discourse/lib/jt-icon-map.ts; do not edit by hand. -->",
  '<svg xmlns="http://www.w3.org/2000/svg">',
  ...[...symbols.values()],
  "</svg>",
  "",
].join("\n");
const licence = readFileSync(join(lucide, "LICENSE"), "utf8");

let stale = false;
for (const [path, content] of [
  [join(theme, "assets/icons-sprite.svg"), sprite],
  [join(theme, "LUCIDE-LICENSE.txt"), licence],
]) {
  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // not built yet
  }
  if (current === content) {
    continue;
  }
  if (check) {
    console.error(`${path} is out of date: run pnpm theme:icons`);
    stale = true;
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}
if (stale) {
  process.exit(1);
}
console.log(
  `${symbols.size} Lucide symbols for ${Object.keys(JT_ICON_MAP).length} icons`
);
